### ISSUE TITLE
elasticsearch/elasticsearch build fails

### ISSUE THREAD

**Issue by sqs** [sourcegraph/srclib-java#6]
For reference, check https://sourcegraph.com/github.com/elasticsearch/elasticsearch/.builds/515877.

The logs from that are:

```

----------------------------- [INFO] BUILD SUCCESS [INFO] ------------------------------------------------------------------------ [INFO] Total time: 35.101s [INFO] Finished at: Tue Sep 16 11:36:57 UTC 2014  2014-09-16 04:36:57 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: [INFO] Final Memory: 14M/222M [INFO] ------------------------------------------------------------------------  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:225: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) {  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:260: warning: '_' used as an identifier  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: try (InternalLock _ = writeLock.acquire()) {  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: ^  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:338: warning: '_' used as an identifier  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: try (InternalLock _ = readLock.acquire()) {  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: ^  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:395: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) { ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:489: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) { ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:585: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) { ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:657: warning: '_' used as an identifier  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: try (InternalLock _ = readLock.acquire()) { ^  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:700: warning: '_' used as an identifier try (InternalLock _ = this.readLock.acquire()) { ^  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:769: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) { ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:817: warning: '_' used as an identifier try (InternalLock _ = writeLock.acquire()) { ^  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:859: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) { ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:896: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) { ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:921: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) { ^  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:989: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) { ^  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:1004: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) { ^  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:1062: warning: '_' used as an identifier  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: try (InternalLock _ = readLock.acquire()) { ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:1074: warning: '_' used as an identifier try (InternalLock _ = writeLock.acquire()) { ^  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:1159: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) { ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:1179: warning: '_' used as an identifier try (InternalLock _ = readLock.acquire()) { ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:1260: warning: '_' used as an identifier try (InternalLock _ = writeLock.acquire()) { ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/index/engine/internal/InternalEngine.java:1481: warning: '_' used as an identifier  2014-09-16 04:36:59 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: try (InternalLock _ = readLock.acquire()) { ^ (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:37:00 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/search/aggregations/Aggregator.java:341: warning: '_' used as an identifier  2014-09-16 04:37:00 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: try (Releasable _ = recordingWrapper) { ^  2014-09-16 04:37:00 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: (use of '_' as an identifier might not be supported in releases after Java SE 8)  2014-09-16 04:37:06 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: src/main/java/org/elasticsearch/search/internal/InternalSearchHit.java:423: error: reference to field is ambiguous builder.field(fieldName, field.value()); ^ both method field(java.lang.String,org.joda.time.ReadableInstant) in org.elasticsearch.common.xcontent.XContentBuilder and method field(java.lang.String,java.util.Date) in org.elasticsearch.common.xcontent.XContentBuilder match  2014-09-16 04:37:09 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: Exception in thread "main"  2014-09-16 04:37:09 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: java.lang.AssertionError: isSubClass Request  2014-09-16 04:37:09 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: at com.sun.tools.javac.code.Symbol.isSubClass(Symbol.java:447) at com.sun.tools.javac.code.Symbol.isMemberOf(Symbol.java:456) at com.sun.tools.javac.code.Symbol$MethodSymbol.overrides(Symbol.java:1469) at com.sun.tools.javac.code.Types$ImplementationCache.implementationInternal(Types.java:2671) at com.sun.tools.javac.code.Types$ImplementationCache.get(Types.java:2653) at com.sun.tools.javac.code.Types.implementation(Types.java:2682) at com.sun.tools.javac.code.Symbol$MethodSymbol.implementation(Symbol.java:1529) at com.sun.tools.javac.code.Symbol$MethodSymbol.implementation(Symbol.java:1518) at com.sun.tools.javac.comp.Resolve.notOverriddenIn(Resolve.java:416) at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:402) at com.sun.tools.javac.comp.Resolve.isAccessible(Resolve.java:362) at com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1448) at com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1618) at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1710) at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1662) at com.sun.tools.javac.comp.DeferredAttr$DeferredChecker$2.lookup(DeferredAttr.java:1325) at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3325) at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3310) at com.sun.tools.javac.comp.DeferredAttr$DeferredChecker.quicklyResolveMethod(DeferredAttr.java:1333) at com.sun.tools.javac.comp.DeferredAttr$DeferredChecker.visitApply(DeferredAttr.java:1223) at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465) at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49) at com.sun.tools.javac.comp.DeferredAttr$FilterScanner.scan(DeferredAttr.java:901) at com.sun.tools.javac.comp.DeferredAttr.isDeferred(DeferredAttr.java:1088) at com.sun.tools.javac.comp.Attr.attribArgs(Attr.java:701) at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1834) at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465) at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607) at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:649) at com.sun.tools.javac.comp.Attr.visitVarDef(Attr.java:1093) at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:852) at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607) at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:676) at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:692) at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1142) at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909) at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607) at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:676) at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1035) at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778) at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607) at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:676) at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4342) at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4252) at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4181) at com.sun.tools.javac.comp.Attr.visitClassDef(Attr.java:892) at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:693) at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:607) at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:676) at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4342) at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4252) at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4201) at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4181) at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4156) at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)  2014-09-16 04:37:09 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1221) at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:364) at com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:344) at com.sourcegraph.javagraph.Grapher.graph(Grapher.java:89) at com.sourcegraph.javagraph.Grapher.graph(Grapher.java:77) at com.sourcegraph.javagraph.GraphCommand.Execute(GraphCommand.java:223) at com.sourcegraph.javagraph.Main.main(Main.java:36)  2014-09-16 04:37:09 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: exit status 1  2014-09-16 04:37:09 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: EOF  2014-09-16 04:37:09 -0700 -0700 1935a7901ab1 Bb21x-T1gon6: command failed: src tool --methods docker "sourcegraph.com/sourcegraph/srclib-java" "graph" < .srclib-cache/99f91f76167b6edb9d6e9fd79f70d679706cab08/org.elasticsearch/elasticsearch/JavaArtifact.unit.json | src internal normalize-graph-data 1> .srclib-cache/99f91f76167b6edb9d6e9fd79f70d679706cab08/org.elasticsearch/elasticsearch/JavaArtifact.graph.json (exit status 1) 
```

**Comment by alexsaveliev** [comment]
claimed fixed by #72
